/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 0$
 * $Date: 0000-00-00$
 */

using System;

namespace ScarygirlTool
{
	public static partial class SvnRevision
	{
		public const Int32  SVN_REV = 0;
		public const String SVN_REVSTR = "0";
		public const String SVN_REVDATE = "0000-00-00";
		public const Int64  SVN_REVSTAMP = 00000000;
		public const Int32  SVN_REVMODIFIED = 0;
	}
}
